### ISSUE TITLE
work out making textures for each armor

### ISSUE THREAD

**Issue by SinaMegapolis** [SinaMegapolis/MoreDyeableArmors#4]
the most important problem on making support for each armor is the fact that the mod needs to get the texture (also the items texture) from somewhere (probably armor material?) and make it "white" (decrease its saturation to zero) so it can get dyed without worrying about the color of texture and armor getting combined. this has to be done mostly throughout BufferedImage and Color since its pretty much a java thing. and the result should be saved in a Map alongside the normal texture so the armor can work fine

**Comment by Burgersim** [comment]
Also, what is your discord? Because I could maybe help you with texturing armor, if you still needed it.

**Comment by SinaMegapolis** [comment]
here's the link: https://discord.gg/D4pKGh
and uh texturing? yes i would like someone to make "overlay" textures for armors that i'm going to add (basically base metals) but normal textures are easy you just make them have zero saturation :P
