### ISSUE TITLE
mirroring behavior from parent item

### ISSUE THREAD

**Issue by SinaMegapolis** [SinaMegapolis/MoreDyeableArmors#5]
you see another important problem is that the new dyeable version of the armor doesn't extend the parent itemarmor (to prevent hard dep) so it will not mirror the parents behavior effectivly.

The best way to solve this problem would be making a wrapper item that gets an itemstack (with the itemarmor as its item) from recipes, attach it to a Capability and call methods from the itemstack's item but include the code to make it dyeable.

**Comment by Gegy** [comment]
You could also delegate all behaviour, though this may not work as well.

**Comment by SinaMegapolis** [comment]
but using a wrapper item could break mods that have anything to do with the armor
saying this, DarkCow suggests using a capability (or NBT Tag?) alongside a render Layer instead
the capability attaches color data to the armor and the render layer gets the data from the cap, using it to render the armor texture +an overlay texture made in the mod itself based on the normal armor texture... the issue making armors dyeable this wasy has is that it can't color the ItemArmor

**Comment by SinaMegapolis** [comment]
correction: it can color the itemarmor but it can't add a layer of overlay texture to the itemarmor

for that there should be an IBakedModel (for each slot?) that combines the model of the parent itemarmor with a model that has only a layer of overlay texture and then register a new instance of IBakedModel for each itemarmor of that slot type in ModelBakeEvent
shadows does this basically but for his jarblocc:
https://github.com/Shadows-of-Fire/Plants/blob/master/src/main/java/shadows/plants2/client/JarItemModel.java
